travis:
  secure:
    BINSTAR_TOKEN: SEu112vzrK2sbSD0Yad8t+gQyfpESZ5rC3AE5rUDpzL8IL9Xl2eRZRc5y2qeZm0vdqlj20mFF2dswkA/JIQLGfOxIM3Ao9JkedWq5UutqFbgYwTiwamyoXb6cp/IZkAPhCbNVs+pbELgYOZqX/gTvSTRftG+r1ESlJYlsD/Qlp3RSvhJmKP1TkcyS5DA5oi21cEw4RjvEWT2HIDZ9OgyJ3JesQaQM2BWN5jTl94Zbuw0vrR4P4aFDSomQ70AZhjti6gWb6FsXkjGBxKIq2inVGBJpdXEePavxjkkmfvYeBAtOjmxh5Wev8VzgZ8+kXZtlB+YGmZOhv4Ga3qa7t6+TvGsqI/ugpvR8d7Dbvazy5Dmu+5XprWlzsr3alcmCyLZ/ChwxmM+W+7vXFaD8PzXbxyp3CgShJ32Wre3w7o7Vs38cGGd6/Eh4v++VCYmb1DMjk1WI+DEsbpUPPBuQ9Gv1JdkLjg6jJIPZ5IhsXmIWxWl50CKAwiIUsLuQUr4zQJB+l8rJNkwfhh2gAHCK499tZsTr67mSFj6GSqVkI9B8Z0rbSKnHE0uqV0WYFrR9AIMWYAaOXYcEIOx079ypS/beazTbIkPuLI+5MX/DTsXJVTL3H2IdgcmJmHXQA7oypGM58Bju8DSH/sQ1V/8lE+Eba5onjvTwDnQYxKr7e7b6NA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
