travis:
  secure:
    BINSTAR_TOKEN: RJwTKdmoeYI7YkkRIU+8DGCyxN9pduSZ2YcqNd8F8kU8SoN2sORHZVjqqvd6xMGaPL7W5Bll6OOjPa3/m3WL5EXU6fbfimSnIYgsRf+KqGAftpYaSzaTmgfd1wjHi+4kAjKjhOwjD6+r2VPUvh2nkRBE6WwZY2nLcJsiFcG2P3PPjOr+Zy5q4fkqR7hl60vY7KDmup+MlJvpRln1b7JH8xnexTAw1/e/+xRuuDrqxRvg/H+Nr6NOKdO7Ruu5eetLP/4svR5cJmoiuS4bngkUH2mwqRXb/rS6GOyo1IUxRruCfElQ6eqT1iAWJ4yMXgJaxjyRbJqzN1kHRyM1IwaTtrtQUQt5k/VQPACAYGzVCC1CgumeFpDjpBzxdLPCAK4EI5cpbC4ff7eWGoP1GYt1Ixe7qYwFyUH21MhOcd1oB70qjsh6eZ+wkzc52I8fvyCdUIaXGbdfUo42CiLp6naQ3dS/lQTZQExX1ZXXvxeeaZpztwReH2bD19iDNhlqI25PFEynforATiCsZJzF0ELXmcw79aGinXs76tEo/67PvfkW6vcWguvJvAiEKCt7VL7iFLt3us6ZsZGCNl+4cCrLUr2LOKXKhtbrBqntcqGWm8mpXJ9xj+m5I6przlsNGWw9uzgTcuT9pHl1GiVGu65TwF6XG2Omzw/VD4751lKQsrM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
